### ISSUE TITLE
[Feature] eCommence vertical (DRAFT)

### ISSUE THREAD

**Issue by noinarisak** [udplabs/zartan#121]
**Is your feature request related to a problem? Please describe.**
eCommerce vertical to demo Okta in b2c situation. 

**Describe the solution you'd like**
This vertical should demonstrate the following use case:
* Progress Profiling
  * Use start with minimal information like email. As they interact with the commence site we get more attributes from the user. (ie. The user wants more info, they have to subscribe to the newsletter, etc)
  * Guest login for checkout.
  * Profile update, self-service MFA, password reset, simple consent

**Describe alternatives you've considered**
Custom

**Additional context**
n/a

**Comment by dzadikdev** [comment]
Need to move website to mobile as a separate feature.

**Comment by dzadikdev** [comment]
How would the flow for the guest checkout work?
