### ISSUE TITLE
[BUG] Registration success message issue 

### ISSUE THREAD

**Issue by mdorn** [udplabs/zartan#238]
**Describe the bug**

Message after user registration does not contain email address, it says "Success! An email message was sent with an activation link to . Please click ..."

**To Reproduce**

Using the "credit" template, click "Apply" and register an account.

**Expected behavior**

Message should either say "Success! Check your email for an activation link." or display the message as described above, but with the email addres.

**Screenshots**

![image](https://user-images.githubusercontent.com/81092/87202840-05371d80-c2c7-11ea-8489-fafc643adcb1.png)

**Comment by noinarisak** [comment]
Say the template is not getting an email variable in Jinja it seems.

https://github.com/udplabs/zartan/blob/4b6c2f99a67e892ef9a8a6673e0de60ecf1c5d8a/GlobalBehaviorandComponents/templates/registration-completion.html#L15-L19

https://github.com/udplabs/zartan/blob/5bb6932633f7981d4fe8abf1d58e6fe96b254a65/_dealer/templates/dealer/registration-completion.html#L10-L13

Wondering why it's in two location thou if this should be global. Hmm

**Comment by jayanthv86** [comment]
If I disable CORS for the Zartan URL in my Okta tenant, and I click on the custom registration page: http://localhost:8666/registration 

And I put in a user it displays a success.
Also, if I put in a user that already exists in my tenant, it shows success even though registration failed.

**Comment by dzadikdev** [comment]
Fixed in release 9fae2de4fa2a2e925e4baea94c3e5f8f611d0e9c
