### ISSUE TITLE
[BUG] Changing APP-LOGINMETHOD does not workin in UDP

### ISSUE THREAD

**Issue by noinarisak** [udplabs/zartan#249]
**Describe the bug**
When you change APP-LOGINMETHOD in UDP it does not change the Login screens/process. 

**To Reproduce**
1. Go to UDP 
2. Update setting for Healthcare for `app_loginmethod="custom-widget"` and click save.
3. Re-launch healthcare, no change. 
4. Click `clear` and refresh no change. 

**Expected behavior**
When I change `app_loginmethod` to another value the UI change. 

**Screenshots**
![Screen Shot 2020-07-16 at 10 33 17 AM](https://user-images.githubusercontent.com/341437/87691301-11502e80-c750-11ea-8eb5-93fd1cf55dd1.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by noinarisak** [comment]
Blocking our Load testing for Sign-In flow.

**Comment by dzadikdev** [comment]
Issue was with wrong environment.
