### ISSUE TITLE
[BUG] Issue when creating multiple credit cards

### ISSUE THREAD

**Issue by dzadikdev** [udplabs/zartan#260]
**Describe the bug**
When creating multiple Credit Card apps under the same UDP Tenant the credit card did not work.

**To Reproduce**
1.  Create 2 Credit Card apps under the same tenant
2. Setup 2 apps to use app and okta login
3. login to one app
4. go to page for managing credit cards
5. click on second app
6. see if auto-login works for second app.

**Expected behavior**
Able to login to one application and click to login to second. User should be able to login.

**Screenshots**
NA

**Desktop (please complete the following information):**
NA
**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by noinarisak** [comment]
close #259
