### ISSUE TITLE
[BUG] Credit App and Dealer App need custom group for multiple deployments

### ISSUE THREAD

**Issue by dzadikdev** [udplabs/zartan#265]
**Describe the bug**
Collision of user to groups when deploying multiple sites to same tenant

**To Reproduce**
1. Create multiple apps on same tenant
2. Try to use app correctly

**Expected behavior**
Should be able to login smoothly

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by noinarisak** [comment]
Looks like we can close this bc of #266
