### ISSUE TITLE
[BUG] Implicit Flow Not Enabled on Auth Server

### ISSUE THREAD

**Issue by dzadikdev** [udplabs/zartan#273]
**Describe the bug**
Need Implicit Flow enabled on Auth Servers for use with Step Up Auth

**To Reproduce**
1. Enable Step Up Auth on Demo
2. Error during step up 

**Expected behavior**
Step up Auth Should Work

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by noinarisak** [comment]
I believe this resolved. @dzadikdev @bhanchand can you confirm?

**Comment by dzadikdev** [comment]
Confirmed.
