### ISSUE TITLE
[BUG] Bad Box folder link in lab prework readme instructions.

### ISSUE THREAD

**Issue by jimfaut-okta** [udplabs/zartan#285]
**Describe the bug**
The Box link in the prework is not working.  The step is for retrieve an API Key for SPARKPOST_API_KEY.  The box folder is 
https://okta.box.com/s/cgp429sqbbowuuyiqgckq6t836lyp8jw

**To Reproduce**
File: README.md

**Comment by noinarisak** [comment]
@jimfaut-okta It worked for. Ping us at #udp-feedback-questions if you are still having access issue, since GitHub is primarily for Zartan development bug/feature-request. ***NOT*** really SE Summit related. 

Sorry for the confusion! =)
