### ISSUE TITLE
[BUG] IDP Redirect breaks on Federated Login

### ISSUE THREAD

**Issue by dzadikdev** [udplabs/zartan#326]
**Describe the bug**
User gets 404 when using Federated Login

**To Reproduce**
1. Go to Zartan App
2. Login with Federated User
3. Receive 404

**Expected behavior**
User logs in normally

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by noinarisak** [comment]
Closed #327
