### ISSUE TITLE
[BUG] Registration page on the local dealer app and UDP dealer app is different

### ISSUE THREAD

**Issue by jayanthv86** [udplabs/zartan#372]
I created the Dealer app in UDP and on my local as well. 

During the custom registration the roles doesn't show up in my local. 

Is there additional config required on the local app?

![image (3)](https://user-images.githubusercontent.com/13931299/93934689-88c2b100-fcf1-11ea-89e4-552e6baf23b0.png)
![image (2)](https://user-images.githubusercontent.com/13931299/93934691-895b4780-fcf1-11ea-9d59-fd8d37dee898.png)

**Comment by dzadikdev** [comment]
Hi @jayanthv86 , Did you run the terraform for the Dealer Demo?

**Comment by jayanthv86** [comment]
@dzadikdev @bhanchand Yes, I ran the dealer terraform scripts

**Comment by srecinto** [comment]
Mike Macomber pinged me for a status update on this.  This appease to be affecting a demo Jay is working on.  If anyone has any spare cycles to dig into it, please do :)

**Comment by noinarisak** [comment]
@jayanthv86 Just a sanity check, if you got the latest and the git commit sha matches what is in `master`.

**Comment by dzadikdev** [comment]
Issue seemed to be local
