### ISSUE TITLE
[FEATURE] Reverse the Matrix Feature vs Vertical App in the README

### ISSUE THREAD

**Issue by noinarisak** [udplabs/zartan#391]
**Is your feature request related to a problem? Please describe.**
Reverse the matrix, having the Feature/Use Case as a single column vs across would provide increase readability and allow a path for more addition to Zartan.

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
n/a

**Additional context**
![Screen Shot 2020-11-10 at 12 46 29 PM](https://user-images.githubusercontent.com/341437/98718175-b1f7d900-2353-11eb-9947-d8c6b8e52b0b.png)

**Comment by keithledgerwood** [comment]
@noinarisak - pull request created.
