### ISSUE TITLE
[BUG] 'Undefined' appears in Factor dropdown list.

### ISSUE THREAD

**Issue by noinarisak** [udplabs/zartan#407]
**Describe the bug**
User sees `undefined` in the dropdown list of both E-commerce and Healthcare vertical when selecting to add Factor. Zartan only supports the following Factors OOTB:

- Google Authenticator
- Okta Verify Push
- SMS
- Voice Call
- Security Question

**To Reproduce**

In Ecommerce vertical and sign in.
1. Enable factor that is not in the above list. 
2. Go to 'Hi {user name} > Profile'
3. Click on 'Add a new factor'
4. Select Factor dropdown list.
4. See screenshot.

**Expected behavior**

**Screenshots**
![Screen Shot 2020-12-07 at 11 28 06 AM](https://user-images.githubusercontent.com/341437/101403930-89ec8e80-389b-11eb-8ee5-acbbac973337.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: 87

**Additional context**

**Comment by noinarisak** [comment]
Let also add in the README what Zartan factors that support OOTB.

**Comment by dzadikdev** [comment]
removed all undefined/unsupported custom enrollment factors from the list.

**Comment by noinarisak** [comment]
Didn't see PR tied to issue @dzadikdev unless it PR that was merged already?

**Comment by dzadikdev** [comment]
No PR was required as the code changes required were only javascript and hosted in our S3 bucket. So the code never was deployed to the servers but instead updated on S3.
