### ISSUE TITLE
[BUG] The JWT parser that displays the ID Token and Access Token is not properly displaying the iat, and exp timestamps.

### ISSUE THREAD

**Issue by kklitzke** [udplabs/zartan#409]
The JWT parser that displays the ID Token and Access Token is not properly displaying the iat, and exp timestamps. 

1. Login as an end user into the finance demo.  This likely impacts all demos.
2. Got to the profile page.
3. Select the ID Token or Access Token tabs on the profile page.
4. Scroll down to the exp or iat values for the JWT Token that is displayed. 

The proper timestamp should be displayed next to these values.   However instead they are empty.

![image](https://user-images.githubusercontent.com/75768848/101717598-d3d0a280-3a5c-11eb-9604-e3d100b48588.png)

Upon investigation it seems to be due to the class associated with the iat and exp values.  After removing the "tooltip" class from the element the value is displayed correctly
![image](https://user-images.githubusercontent.com/75768848/101717698-0e3a3f80-3a5d-11eb-9bfd-1dd378e81757.png)

**Comment by dzadikdev** [comment]
Fix complete on JS side
