### ISSUE TITLE
[FEATURE] Add WebAuthn for Factor Enrollment

### ISSUE THREAD

**Issue by dzadikdev** [udplabs/zartan#410]
**Is your feature request related to a problem? Please describe.**
Add webauthn as a factor enrollment option

**Describe the solution you'd like**
Add webauthn as a factor enrollment option

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dzadikdev** [comment]
Delayed due to product enhancement requirements for custom domains.

**Comment by noinarisak** [comment]
Close PR #415
