### ISSUE TITLE
[BUG] Feature Matrix does not have the correct information

### ISSUE THREAD

**Issue by noinarisak** [udplabs/zartan#419]
**Describe the bug**
The feature identifies that both Credit and Finance do not have `Consent` functionality.

**To Reproduce**
n/a

**Expected behavior**
The correct information.

**Screenshots**
![Screen Shot 2021-02-22 at 10 49 26 AM](https://user-images.githubusercontent.com/341437/108741010-e2771380-74fb-11eb-9fa9-439586b533c5.png)

**Desktop (please complete the following information):**
 n/a 

**Additional context**
n/a

**Comment by dzadikdev** [comment]
Looks good.
