### ISSUE TITLE
Terraform Scripts for each vertical to migrate to UDP

### ISSUE THREAD

**Issue by srecinto** [udplabs/zartan#50]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by noinarisak** [comment]
Will, the following use case exists: 

SE under a single subdomain (Okta tenant) spawn two instances of Zartan with different verticals?

UDP will have to allow multiple instances of Zartan to exist if the above is true.

**Comment by noinarisak** [comment]
The expectation is all the Zartan verticals can exist in single Okta org. 

Closed #128
