### ISSUE TITLE
Hook in logger to all components and remove print statements

### ISSUE THREAD

**Issue by srecinto** [udplabs/zartan#69]
**Is your feature request related to a problem? Please describe.**
Zartan logging approach needs and remove `print` statement.

**Describe the solution you'd like**
Consider keeping the Flask logging and use https://rollbar.com/error-tracking/flask/ or https://sentry.io/for/flask/ combination with localhost logging. 

**Describe alternatives you've considered**
Short term solution is to just following Flask logging https://flask.palletsprojects.com/en/1.1.x/logging/

**Additional context**
N/A

**Comment by noinarisak** [comment]
Update the issue with more context.

**Comment by srecinto** [comment]
Good point.  those other two look like paid services but i'll look into the app.logger since it is already configured
