### ISSUE TITLE
Add flake8 linter and perform code clean up once stable

### ISSUE THREAD

**Issue by srecinto** [udplabs/zartan#70]
**Is your feature request related to a problem? Please describe.**
Add flake8 linting for code quality

**Describe the solution you'd like**
GitHub Action that will execute flake8 on a PR. Enforcing some code quality and standard.

**Describe alternatives you've considered**
Running manually on local development machine.

**Additional context**
N/A

**Comment by noinarisak** [comment]
Update the issue.

**Comment by noinarisak** [comment]
I can author Makefile that will contain flake8 and skeleton for pytest (unit test)
